name: Data enrichment
language: Python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: csv-data
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: enriched-data
    required: false
  - name: redis_host
    inputType: FreeText
    description: ''
    defaultValue: redis-18174.c304.europe-west1-2.gce.redns.redis-cloud.com
    required: true
  - name: redis_port
    inputType: FreeText
    description: ''
    defaultValue: 18174
    required: false
  - name: redis_username
    inputType: FreeText
    description: ''
    defaultValue: ''
    required: false
  - name: redis_password
    inputType: Secret
    description: ''
    defaultValue: redis_password
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
