name: Data enrichment
language: Python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: csv-data
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: enriched-data
    required: false
  - name: redis_host
    inputType: FreeText
    description: ''
    defaultValue: ''
    required: false
  - name: redis_port
    inputType: FreeText
    description: ''
    defaultValue: ''
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
